name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set the Python version you need

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev build-essential python3-dev python3-venv git zip unzip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Buildozer Init (if buildozer.spec does not exist)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          buildozer android debug
        env:
          ANDROID_NDK_HOME: ${{ secrets.ANDROID_NDK_HOME }}
          ANDROID_SDK_HOME: ${{ secrets.ANDROID_SDK_HOME }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: bin/*.apk
